const shared = [
  "When you finish drafting or updating a Markdown plan/spec, hand it to the",
  "human through Spec Reviewer before treating the spec as accepted.",
  "",
  "## Workflow",
  "",
  "1. Save the Markdown spec to disk.",
  "2. Run:",
  "",
  "   ```bash",
  "   spec-reviewer review path/to/spec.md --wait --json",
  "   ```",
  "",
  "3. Wait for the human to click Finish Review or Cancel.",
  "4. If the command exits non-zero or returns `status: \"canceled\"`, stop and",
  "   report that the review was canceled.",
  "5. If it returns `status: \"finished\"`, read the `markdown` field and apply",
  "   every requested change.",
  "6. Run the relevant project checks for the changed spec or plan.",
  "7. Report what changed and how it was verified.",
  "",
  "## Durable Handoffs",
  "",
  "For a local source file, the app saves an immutable handoff checkpoint before",
  "**Handoff & copy** writes feedback to the clipboard. A finished `--wait` review",
  "also creates an immutable finish checkpoint. Both checkpoints preserve the",
  "exact source used for the feedback, so the human can reopen the review after",
  "your edits and inspect a real diff. Dropped uploads remain immutable and do",
  "not create a comparison baseline.",
  "",
  "Do not claim that copied feedback was addressed just because its source text",
  "moved or disappeared. The human must confirm moved, ambiguous, or missing",
  "anchors before resolving those notes.",
  "",
  "## Reopen Drift Check",
  "",
  "When the human wants to inspect whether feedback still lines up after your",
  "edits, choose the reopen path that matches the review state:",
  "",
  "For a saved review, list sessions and reopen the matching one:",
  "",
  "```bash",
  "spec-reviewer sessions --json",
  "spec-reviewer open <session-id>",
  "```",
  "",
  "For a checkpoint-only review that is not listed in sessions, reopen the",
  "known source path directly:",
  "",
  "```bash",
  "spec-reviewer review path/to/spec.md",
  "```",
  "",
  "Use the applicable command after a handoff or finished review when the human",
  "wants to inspect your edits against the saved baseline.",
  "",
  "## Rules",
  "",
  "- Do not edit the reviewed spec automatically from inside Spec Reviewer.",
  "- Do not mark review feedback complete until you have applied it and run",
  "  appropriate verification.",
  "- Preserve the original spec path; dropped files may be copied into",
  "  `~/.spec-reviewer/documents` by the browser.",
  "- Prefer the Homebrew-installed `spec-reviewer` binary.",
].join("\n");

const codexFrontmatter = [
  "---",
  "name: spec-reviewer",
  "description: Use after drafting or updating Markdown specs or plans when human review feedback should be collected through the local Spec Reviewer app.",
  "---",
  "",
].join("\n");

const claudeFrontmatter = [
  "---",
  "name: spec-reviewer",
  "description: Use after drafting or updating Markdown specs or plans when human review feedback should be collected through the local Spec Reviewer app.",
  "---",
  "",
].join("\n");

export type SkillTarget = "codex" | "claude";

export function skillTemplate(target: SkillTarget): string {
  const title = target === "codex" ? "# Spec Reviewer For Codex" : "# Spec Reviewer For Claude Code";
  const frontmatter = target === "codex" ? codexFrontmatter : claudeFrontmatter;
  return `${frontmatter}${title}\n\n${shared}\n`;
}
